/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RukhGovernanceToken__factory } from "./RukhGovernanceToken__factory";
export { RukhGovernor__factory } from "./RukhGovernor__factory";
