/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RukhGovernanceToken } from "./RukhGovernanceToken";
export type { RukhGovernor } from "./RukhGovernor";
